#
# ********* LIVE VALUES FOR DEPLOYING DAPR-STORE APP *******
# install with
#  helm install store ~/dev/dapr-store/deploy/helm/daprstore --values ~/dev/dapr-store/deploy/live/app-values.yaml --namespace dapr-store
#
# OPTIONAL: Deploy custom components
#  kubectl apply -f ~/dev/dapr-store/components/orders-report.yaml
#  kubectl apply -f ~/dev/dapr-store/components/orders-email.yaml
#

image:
  tag: "0.8.3"

# Manually configured in DNS
ingress:
  host: "daprstore.kube.benco.io"
  certName: "kube-benco-io-cert"

# Enable auth
auth:
  clientId: "69972365-c1b6-494d-9579-5b9de2790fc3"
# cart:
#   annotations:
#     dapr.io/config: "custom-config"
#     dapr.io/log-level: "debug"
