apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-orders
  labels:
    {{- include "daprstore.labels" . | nindent 4 }}
    daprstore: orders
    
spec:
  replicas: {{ .Values.orders.replicas }}
  selector:
    matchLabels:
      daprstore: orders
  template:
    metadata:
      labels:
        daprstore: orders
        {{- include "daprstore.selectorLabels" . | nindent 8 }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orders"
        dapr.io/app-port: "9004"
      {{- with .Values.orders.annotations }}
          {{- toYaml . | nindent 8 }}
      {{- end }}            
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}    

      containers:
      - name: server
        image: {{ .Values.image.registry }}/{{ .Values.image.repo }}/orders:{{ .Values.image.tag }}
        imagePullPolicy: Always

        {{- if .Values.auth.clientId }}
        env:
          - name: AUTH_CLIENT_ID
            value: {{ .Values.auth.clientId }}
        {{- end }} 

        resources:
        {{- with .Values.resources }}
          {{- toYaml . | nindent 10 }}
        {{- end }}

        readinessProbe:
          httpGet:
            path: /health
            port: 9004
            httpHeaders:
              - name: "No-Log"
                value: "true"
