#@host = staging.daprstore.benco.io
#@host = daprstore.kube.benco.io
@host = localhost:9000

# ===================================================================
# Products API
# ===================================================================

GET http://{{host}}/v1.0/invoke/products/method/catalog

###

GET http://{{host}}/v1.0/invoke/products/method/offers

###

GET http://{{host}}/v1.0/invoke/products/method/get/prd003

###

GET http://{{host}}/v1.0/invoke/products/method/search/Paisley



# ===================================================================
# Cart API
# ===================================================================

### Add products to cart
PUT http://{{host}}/v1.0/invoke/cart/method/setProduct/demo@example.net/prd001/6

### Get cart
GET http://{{host}}/v1.0/invoke/cart/method/get/demo@example.net

### Clear cart
PUT http://{{host}}/v1.0/invoke/cart/method/clear/demo@example.net

### Submit cart
POST http://{{host}}/v1.0/invoke/cart/method/submit
content-type: application/json

"demo@example.net"



# ===================================================================
# Orders API
# ===================================================================

### Get existing order
GET http://{{host}}/v1.0/invoke/orders/method/get/yCK1e 

### Get orders for user
GET http://{{host}}/v1.0/invoke/orders/method/getForUser/demo@example.net



# ===================================================================
# Users API
# ===================================================================

### Check a user
GET http://{{host}}/v1.0/invoke/users/method/isregistered/demo@example.net

### Get a user
GET http://{{host}}/v1.0/invoke/users/method/get/demo@example.net

### Register new user
POST http://{{host}}/v1.0/invoke/users/method/register
content-type: application/json

{
  "username": "demo@example.net",
  "displayName": "API TEST"
}
