POST https://api.github.com/repos/benc-uk/dapr-store/actions/workflows/1300956/dispatches
Authorization: Basic benc-uk:{{$dotenv GITHUB_PAT}}
Content-Type: application/json

{
  "ref": "refs/heads/master"
}

###

GET https://api.github.com/repos/benc-uk/dapr-store/actions/workflows
Authorization: Basic benc-uk:{{$dotenv GITHUB_PAT}}

###

POST https://api.github.com/repos/benc-uk/dapr-store/dispatches
Authorization: Basic benc-uk:{{$dotenv GITHUB_PAT}}
Content-Type: application/json

{
  "event_type": "Continuous Deployment",
  "client_payload": {
    "imageTag": "latest"
  }
}

###


POST https://api.github.com/repos/benc-uk/dapr-store/deployments
Authorization: Basic benc-uk:{{$dotenv GITHUB_PAT}}
Content-Type: application/json

{
  "ref": "master",
  "description": "Deploy to AKS cluster",
  "environment": "Kubernetes",
  "payload": {
    "imageTag": "109575027"
  },
  "required_contexts": []
}

###

POST https://api.github.com/repos/benc-uk/dapr-store/deployments/229616751/statuses
Authorization: Basic benc-uk:{{$dotenv GITHUB_PAT}}
Content-Type: application/json
Accept: application/vnd.github.flash-preview+json,application/vnd.github.ant-man-preview+json

{
  "environment": "Foobar",
  "state": "failure",
  "log_url": "https://example.com/deployment/42/output",
  "environment_url": "https://example.com/wibble",
  "description": "Hi"
}


###

DELETE https://api.github.com/repos/benc-uk/dapr-store/deployments/228961438
Authorization: Basic benc-uk:{{$dotenv GITHUB_PAT}}

###

GET https://api.github.com/repos/benc-uk/dapr-store/deployments?environment=AKS
Authorization: Basic benc-uk:{{$dotenv GITHUB_PAT}}

