POST https://api.github.com/repos/benc-uk/dapr-store/deployments
Authorization: Basic benc-uk:{{$dotenv GITHUB_PAT}}
Content-Type: application/json

{
  "ref": "master",
  "description": "Deploy to AKS demo environment",
  "environment": "Kubernetes",
  "payload": {
    "imageTag": "foo123"
  }
}

###

POST https://api.github.com/repos/benc-uk/dapr-store/deployments/228959120/statuses
Authorization: Basic benc-uk:{{$dotenv GITHUB_PAT}}
Content-Type: application/json

{
  "environment": "production",
  "state": "success",
  "log_url": "https://example.com/deployment/42/output",
  "environment_url": "https://example.com/wibble",
  "description": "Deployment finished successfully."
}


###

DELETE https://api.github.com/repos/benc-uk/dapr-store/deployments/228977468
Authorization: Basic benc-uk:{{$dotenv GITHUB_PAT}}

###

GET https://api.github.com/repos/benc-uk/dapr-store/deployments
Authorization: Basic benc-uk:{{$dotenv GITHUB_PAT}}

