@host = localhost:9000
#@host = daprstore.benco.io

# ===================================================================
# Products API
# ===================================================================

GET http://{{host}}/v1.0/invoke/products/method/catalog

###

GET http://{{host}}/v1.0/invoke/products/method/offers

###

GET http://{{host}}/v1.0/invoke/products/method/get/1



# ===================================================================
# Orders API
# ===================================================================

### Get an order
GET http://{{host}}/v1.0/invoke/orders/method/get/fo6zn

### Create new order
POST http://{{host}}/v1.0/invoke/orders/method/new
content-type: application/json

{
  "items": ["1","3"],
  "amount": 34.7
}



# ===================================================================
# Users API
# ===================================================================

### Get a user
GET http://{{host}}/v1.0/invoke/users/method/get/becolem@microsoft.com

### Register new user
POST http://{{host}}/v1.0/invoke/users/method/register
content-type: application/json

{
  "username": "bobby@example.com",
  "displayName": "Dave McTestman"
}
 