@host = localhost:9000
#@host = daprstore.kube.benco.io

# ===================================================================
# Products API
# ===================================================================

GET http://{{host}}/v1.0/invoke/products/method/catalog

###

GET http://{{host}}/v1.0/invoke/products/method/offers

###

GET http://{{host}}/v1.0/invoke/products/method/get/1



# ===================================================================
# Cart API
# ===================================================================

### Create new order
POST http://{{host}}/v1.0/invoke/cart/method/submit
content-type: application/json

{
  "items": ["1","3"],
  "amount": 34.7,
  "forUser": "becolem@microsoft.com"
}



# ===================================================================
# Orders API
# ===================================================================

### Get existing order
GET http://{{host}}/v1.0/invoke/orders/method/get/WK728



# ===================================================================
# Users API
# ===================================================================

### Check a user
GET http://{{host}}/v1.0/invoke/users/method/isregistered/benc.uk@outlook.com

### Get a user
GET http://{{host}}/v1.0/invoke/users/method/get/benc.uk@outlook.com


### Register new user
POST http://{{host}}/v1.0/invoke/users/method/register
content-type: application/json

{
  "username": "becolem@microsoft.com",
  "displayName": "Ben API TEST"
}
 
### Add order to user
PUT http://{{host}}/v1.0/invoke/users/method/addorder/benc.uk@outlook.com/3GBSh

 